### ISSUE TITLE
PowerToys submission considered?

### ISSUE THREAD

**Issue by robmonte** [SamsidParty/TopNotify#13]
Do you know if this was written in such a way that it'd be compatible with [PowerToys](https://github.com/microsoft/PowerToys/)? It would be neat if you submitted it as a feature for it, if compatible. This is such a great feature that deserves more recognition, thank you so much for your efforts.

**Comment by SamsidParty** [comment]
As powertoys is more suited towards utilities rather than customization, it's not likely to be implemented.
Also, similar feature requests were rejected because it's "a feature of windows".

However, it's worth trying, so you can find the request we submitted [here](https://github.com/microsoft/PowerToys/issues/33237)
