### ISSUE TITLE
Feature Request: Change Notification background Material

### ISSUE THREAD

**Issue by Skyyblaze** [SamsidParty/TopNotify#27]
First of all I want to thank you for creating this awesome program, ever since Windows 10 and now Windows 11 the default notification positioning has driven me up a wall. Countless times I wanted to interact with something in the bottom right corner only for a notification to bump in and block everything so I would pay for TopNotify if I had to, it's that good haha.

I have one feature request though I'm not even sure is possible. Notifications are by default rendered with the "Mica Material" background in Windows 11, would it be possible for TopNotify to change that to Mica Alt or Acrylic even so the background of the notification has a Aero-style transparency?

There are other programs such as ExplorerBlurMica , MicaForEveryone and DWMBlurGlass (All open-source on Github) that can override the default Mica style of the Windows 11 explorer (and other apps) with Mica Alt or Windows 10 Acrylic transparency so I wondered if TopNotify could do the same for the background of notifications.

ExplorerBlurMica: https://github.com/Maplespe/ExplorerBlurMica/
MicaForEveryone: https://github.com/MicaForEveryone/MicaForEveryone
DWMBlurGlass: https://github.com/Maplespe/DWMBlurGlass

I'm not sure if this is within the scope of TopNotify though. Either way thanks again for creating the program, it already made my Windows 11 life so much more less frustrating.

**Comment by SamsidParty** [comment]
The thing is, the notification window itself doesn't have any background effects, it's pure transparent.
Only the UI inside it has an effect (which is acrylic btw, not mica). I will try anyway, since TopNotify (more specifically IgniteView) already has the code to enable mica on it's own GUI window.

**Comment by SamsidParty** [comment]
![image](https://github.com/user-attachments/assets/cb3ceaf2-878f-4dab-aa20-2de6f54f2751)
As I expected, it doesn't work. It affects the entire notification window, and turns it white instead of making it mica.
In the future, (like, very far ahead) TopNotify may implement a completely custom notification renderer, so we can have complete control of the way it's displayed. For now though, it's not possible.

**Comment by Skyyblaze** [comment]
Wow thanks for the quick testing much appreciated! I never realized that notifications were already Acrylic since they seem so opaque (probably because I have lots of Rainmeter going on in the bottom right corner of my screen but now that I have them elsewhere I see that yeah.

Thanks for the effort though, if a complete theme-system ever happens with TopNotify I'll gladly add a few themes to it. Back in the Windows Vista days I made a Windows Longhorn styled notification-toast, I'm excited to revive that if it becomes possible.

(Also your screenshot perfectly illustrates one thing I hate about the Windows 10/11 notifications, the invisible margin around them is so huge so they cover up even more UI than you would think visually)
