### ISSUE TITLE
Failed to start notification listener

### ISSUE THREAD

**Issue by krasotulya3000** [SamsidParty/TopNotify#31]
Hello!

I hope you are doing well. I am trying to set up TopNotify, but it does not work with an error "Failed to start notification Listener: not packaged". Could you please help me out? What do I need to do?
![IMG_9467](https://github.com/user-attachments/assets/4818edaa-5e3f-439a-848e-13398ea7ceaa)

**Comment by SamarthMP** [comment]
This error should not affect the usage of TopNotify right now, it is for upcoming versions with new features.
Can you confirm if TopNotify is working normally aside from this error?

**Comment by krasotulya3000** [comment]
Hello. It’s not working at all. I make adjustments in settings, but nothing changes at all, and all the notifications are all the same

**Comment by krasotulya3000** [comment]
Actually there is no error now. But still notifications can’t be adjusted
![IMG_9468](https://github.com/user-attachments/assets/b8cdeff0-5cef-438c-8547-24fa52fae67e)

**Comment by SamarthMP** [comment]
I see, well is your system language set to English or something else?

**Comment by krasotulya3000** [comment]
It works now, thanks a lot! Could you please comment on adding features like stacking up notifications or force changing duration (eg 1 sec)

**Comment by SamarthMP** [comment]
Great! I will try to add support for Ukrainian in the next update, however that will be in a while since i'm abroad (around end of October)

The duration of notifications can be changed from the [windows settings](https://www.majorgeeks.com/content/page/how_to_change_the_windows_10_notification_display_time.html).
As for stacking notifications, it's currently not possible since windows will only display one at a time, maybe in the future a custom notification renderer will be implemented.

**Comment by Fummowo** [comment]
Heya, sorry to bump closed issue, but i'm having the same thing on English (United Kingdom) :))

**Comment by SamsidParty** [comment]
Hey @Fummowo, after some investigation, I have found that this happens sometimes on first time launch from the store.
The solution I was able to find was just to restart your computer.
