### ISSUE TITLE
Rollout animation direction

### ISSUE THREAD

**Issue by terax6669** [SamsidParty/TopNotify#35]
It should start at the taskbar and roll out instead of into the taskbar.

https://github.com/user-attachments/assets/dd12183a-840c-4fe5-959b-0e8e4d02bcad

**Comment by SamsidParty** [comment]
Unfortunately this likely can't be fixed without a custom notification renderer.
The notification itself animates from the right and it can't be changed with the window management APIs.

It may be possible to trick windows into animating from the left because that's what it does on RTL languages, but I don't know how I would implement that.
