### ISSUE TITLE
display on top of full screen applications

### ISSUE THREAD

**Issue by anonogey** [SamsidParty/TopNotify#9]
Hello, is it possible to have the notifications display on top of full screen applications like games? Or maybe on a secondary monitor?

**Comment by SamsidParty** [comment]
Hey There!
For games, it’s possible, but you have to set the game to “Windowed Fullscreen” mode or “Borderless Windowed” mode instead of regular fullscreen. You’ll also have to turn off these settings:

￼

As for a second monitor, I don’t have one to test, but the custom notification position might work if you drag the window to another monitor.

**Comment by SamarthMP** [comment]
Don't think the image loaded, here it is:

![image](https://github.com/SamsidParty/TopNotify/assets/79756986/575401f1-6873-4c9f-983a-26078f01baef)

**Comment by anonogey** [comment]
Oh so there is no way to get it working on regular fullscreen? Windowed fullscreen causes issues in certain games for me.

> As for a second monitor, I don’t have one to test, but the custom notification position might work if you drag the window to another monitor.

Tried and notification still only appear on the main monitor.

I guess I can live with a little flicker if there's no other way. Thank you for entertaining my questions.

**Comment by SamarthMP** [comment]
The problem with standard fullscreen is that DirectX creates an isolated context that only the game can draw to.
I will see if I can get multi monitor support in the next version.
